### ISSUE TITLE
Is there

### ISSUE THREAD

**Issue by appernetic** [auth0/webtask-scripts#3]
any instructions on how this works and how to use it?

I am looking for a way to track Payment from my Github authenticated users without using a db. I can do that by adding the github id to stripe when a user pays from my Node.js server. If I instead use this solution (and if it is what I suppose it is?) what would the benefit be?

**Comment by ArSn** [comment]
@appernetic 
There is an exemplary guide available at: https://webtask.io/docs/sample_github
And I think what you are trying to do sounds doable.

What would the benefit be? Simple: You don't have to worry about any hosting at all. Just put your code in the webtask, set up the hook, let it work for you. Done.

**Comment by appernetic** [comment]
I had to use a db when using stripe subscription, there was no way around it. Also it was easier to implement when there wasn't  an extra layer to try to understand.
